title: X-Insights
description: >-
  X-Insights is the Analytics Domain Club of XIME Bengaluru.
  We learn, build and compete in data analytics and AI.
url: ""
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
logo: /assets/images/logo.png
